language: node_js
os: linux
dist: xenial
node_js:
  - 8
  - 9
  - 10
  - 11
  - 12
  - 13
  - 14
jobs:
  include:
    - stage: npm release
      if: tag IS present
      node_js: 14
      deploy:
        provider: npm
        email: rogier+npm@konfirm.eu
        on:
          branch: master
          tags: true
        api_key:
          secure: duCfSodvUMRvg7/oT4IT2OWcCNkY0XLMt9bb2FI0/FusJNltFUktpOOECe/+KEr2/31VB6qKQoHzyMeDtkgEwxc2Qf+slwUA1hYNYUMoU0xDBAT1TV3ZuhBAAvsVbneV1+bA5UBKjAtopyCySm2M//0xJ9H4aKVw6ovXTwQofgQiS4ZRYtDQTUpi+p9nQhZZVnoZgvg7DzbsB/s1aFXmRT4uBprAXhlsoa2peHaADcmUDKdtvNaLCUF5z3Yi/58RaIFnXfsLXmcippyttJ3JJ6cHtL+RtrHXJOuoSj1Szt85jIpK/KkHDlDEHpmzbPN3959p8CIeZAcziEQxmVMBmh0j0e4s9MCg0QsiLQVtr5kMygatgUPy5oJ4XjcxfN3qvEkZN6qyfqimG3x5Gb9AeIA9l+j72nsChFurHtbmCG0tUQwn4ctK8mXp4D/kejW3O5711XrdVnNdM66PH+CujVhlOCIMDCh4xJjtvxtJfaZ1u7IEBU4bJWHEdZtlGA/KnijJV+JfAUYm4H/YmQ0Gtbbbc5uWyJp8vEPkY50vTaKKq3iiw+KQ3XxmeFIavRT4nmHMuoE1iJhvtZZ8ddxgGCgPq0QnVfwcwwid9iQFRMKRGIp0zhMr5H4nRBXcBQqsjdDOxGZjkKKy807Yp0XKc8U4JTfef87CcKPy+O5UjVw=
